import React, { useMemo, useState } from 'react';
import { CalendarDays, Check, Pencil, Plus, Target, Trash2, X } from 'lucide-react';
import { calculateGoalProgress, createGoal, generateRecommendedGoals, workplaceDimensionNames } from '../../data/swellGoals';

const emptyDraft = { title: '', description: '', linkedDimension: '', linkedTrait: '', targetDate: '' };
function GoalModal({ title, children, onClose }) { return <div className="goal-modal-backdrop"><section className="goal-modal"><button className="goal-modal-close" onClick={onClose} aria-label="Close"><X size={20} /></button><h2>{title}</h2>{children}</section></div>; }
function GoalMeta({ goal }) { return <div className="goal-meta">{goal.linkedDimension && <span>Linked to: {goal.linkedDimension}</span>}{goal.targetDate && <span><CalendarDays size={13} /> {goal.targetDate}</span>}</div>; }

export default function SwellGoals({ dashboardData, goals, onGoalsChange }) {
  const [filter, setFilter] = useState('active'); const [addOpen, setAddOpen] = useState(false); const [addTab, setAddTab] = useState('recommended'); const [detailGoalId, setDetailGoalId] = useState(null); const [editingGoalId, setEditingGoalId] = useState(null); const [deleteGoalId, setDeleteGoalId] = useState(null); const [draft, setDraft] = useState(emptyDraft); const [newActionText, setNewActionText] = useState('');
  const recommended = useMemo(() => generateRecommendedGoals(dashboardData), [dashboardData]);
  const visibleGoals = goals.filter((goal) => goal.status === filter).map((goal) => ({ ...goal, progress: calculateGoalProgress(goal) }));
  const update = (next) => onGoalsChange(next);
  const addRecommended = (recommendation) => { if (goals.some((goal) => goal.status === 'active' && goal.title === recommendation.title)) return; update([...goals, createGoal({ ...recommendation, source: 'recommended', actions: recommendation.actions })]); };
  const openCustom = () => { setDraft(emptyDraft); setEditingGoalId(null); setAddTab('custom'); };
  const saveCustom = (event) => { event.preventDefault(); if (!draft.title.trim()) return; const values = { ...draft, title: draft.title.trim(), description: draft.description.trim() || 'A professional development goal.', linkedDimension: draft.linkedDimension || null, linkedTrait: draft.linkedTrait || null, targetDate: draft.targetDate || null }; if (editingGoalId) update(goals.map((goal) => goal.id === editingGoalId ? { ...goal, ...values } : goal)); else update([...goals, createGoal({ ...values, source: 'custom' })]); setAddOpen(false); setEditingGoalId(null); };
  const selectedGoal = goals.find((goal) => goal.id === detailGoalId);
  const patchGoal = (id, patch) => update(goals.map((goal) => goal.id === id ? { ...goal, ...patch } : goal));
  const toggleAction = (goal, actionId) => { const actions = goal.actions.map((action) => action.id === actionId ? { ...action, completed: !action.completed } : action); patchGoal(goal.id, { actions, progress: calculateGoalProgress({ ...goal, actions }) }); };
  const addAction = (goal) => { if (!newActionText.trim()) return; const actions = [...goal.actions, { id: `action-${Date.now()}-${Math.random().toString(16).slice(2)}`, text: newActionText.trim(), completed: false }]; patchGoal(goal.id, { actions, progress: calculateGoalProgress({ ...goal, actions }) }); setNewActionText(''); };
  const completeGoal = (goal) => patchGoal(goal.id, { status: 'completed', progress: 100, completedAt: new Date().toISOString(), actions: goal.actions.map((action) => ({ ...action, completed: true })) });
  const deleteGoal = (id) => { update(goals.filter((goal) => goal.id !== id)); setDeleteGoalId(null); setDetailGoalId(null); };
  const editGoal = (goal) => { setDraft({ title: goal.title, description: goal.description, linkedDimension: goal.linkedDimension ?? '', linkedTrait: goal.linkedTrait ?? '', targetDate: goal.targetDate ?? '' }); setEditingGoalId(goal.id); setAddOpen(true); setAddTab('custom'); setDetailGoalId(null); };

  return <><div className="page-intro with-action"><div><h2>Goals</h2><p>Professional goals based on your evolving Swell profile.</p></div><button className="add-goal" onClick={() => { setAddOpen(true); setAddTab('recommended'); }}><Plus size={17} /> Add goal</button></div><div className="goal-filter"><button className={filter === 'active' ? 'active' : ''} onClick={() => setFilter('active')}>Active</button><button className={filter === 'completed' ? 'active' : ''} onClick={() => setFilter('completed')}>Completed</button></div><div className="goals-list">{visibleGoals.length ? visibleGoals.map((goal) => <article className={`card goal-card functional-goal ${goal.status}`} key={goal.id} onClick={() => setDetailGoalId(goal.id)}><div className="goal-icon"><Target size={18} /></div><div className="goal-body"><div><h3>{goal.title}</h3><b>{goal.progress}%</b></div><p>{goal.description}</p><GoalMeta goal={goal} /><div className="bar"><i className={goal.status === 'completed' ? 'teal' : 'violet'} style={{ width: `${goal.progress}%` }} /></div><small>{goal.actions.length ? `${goal.actions.filter((action) => action.completed).length} of ${goal.actions.length} actions completed` : `${goal.status === 'completed' ? 'Completed' : 'Manual progress'}`}</small></div><button className="goal-overflow" onClick={(event) => { event.stopPropagation(); editGoal(goal); }} aria-label={`Edit ${goal.title}`}><Pencil size={15} /></button></article>) : <div className="goal-empty"><Target size={18} /><span>{filter === 'active' ? 'No active goals yet. Add a recommendation or create your own.' : 'No completed goals yet.'}</span></div>}</div>
  {addOpen && <GoalModal title={editingGoalId ? 'Edit goal' : 'Add goal'} onClose={() => setAddOpen(false)}><div className="goal-modal-tabs"><button className={addTab === 'recommended' ? 'active' : ''} onClick={() => setAddTab('recommended')}>Recommended for you</button><button className={addTab === 'custom' ? 'active' : ''} onClick={openCustom}>Create custom goal</button></div>{addTab === 'recommended' ? <div className="recommendation-list">{recommended.map((recommendation) => <article key={recommendation.title}><div><h3>{recommendation.title}</h3><span>{recommendation.reason}</span><p>{recommendation.description}</p><small>Linked to: {recommendation.linkedDimension}</small></div><button className="assessment-primary" disabled={goals.some((goal) => goal.status === 'active' && goal.title === recommendation.title)} onClick={() => addRecommended(recommendation)}>Add goal</button></article>)}</div> : <form className="goal-form" onSubmit={saveCustom}><label>Goal title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} required /></label><label>Description<textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><label>Linked dimension (optional)<select value={draft.linkedDimension} onChange={(event) => setDraft({ ...draft, linkedDimension: event.target.value })}><option value="">None</option>{workplaceDimensionNames.map((dimension) => <option key={dimension}>{dimension}</option>)}</select></label><label>Linked trait (optional)<input value={draft.linkedTrait} onChange={(event) => setDraft({ ...draft, linkedTrait: event.target.value })} /></label><label>Target date (optional)<input type="date" value={draft.targetDate} onChange={(event) => setDraft({ ...draft, targetDate: event.target.value })} /></label><button className="assessment-primary" type="submit">{editingGoalId ? 'Save changes' : 'Create goal'}</button></form>}</GoalModal>}
  {selectedGoal && <GoalModal title={selectedGoal.title} onClose={() => setDetailGoalId(null)}><p className="detail-description">{selectedGoal.description}</p><GoalMeta goal={selectedGoal} /><div className="detail-progress"><span>Progress</span><b>{calculateGoalProgress(selectedGoal)}%</b><div className="bar"><i className="violet" style={{ width: `${calculateGoalProgress(selectedGoal)}%` }} /></div></div><div className="action-steps"><span>ACTION STEPS</span>{selectedGoal.actions.map((action) => <label key={action.id}><input type="checkbox" checked={action.completed} onChange={() => toggleAction(selectedGoal, action.id)} />{action.text}</label>)}{!selectedGoal.actions.length && <label>Manual progress<input type="range" min="0" max="100" value={selectedGoal.progress} onChange={(event) => patchGoal(selectedGoal.id, { progress: Number(event.target.value) })} /></label>}{selectedGoal.source === 'custom' && <div className="add-action"><input placeholder="Add an action step" value={newActionText} onChange={(event) => setNewActionText(event.target.value)} /><button className="assessment-secondary" onClick={() => addAction(selectedGoal)}>Add step</button></div>}</div><div className="detail-actions"><button className="assessment-secondary" onClick={() => editGoal(selectedGoal)}><Pencil size={15} /> Edit</button>{selectedGoal.status !== 'completed' && <button className="assessment-primary" onClick={() => completeGoal(selectedGoal)}><Check size={15} /> Mark complete</button>}<button className="danger-button" onClick={() => setDeleteGoalId(selectedGoal.id)}><Trash2 size={15} /> Delete</button></div></GoalModal>}
  {deleteGoalId && <GoalModal title="Delete goal?" onClose={() => setDeleteGoalId(null)}><p className="detail-description">This will remove the goal and its action steps from your local demo data.</p><div className="detail-actions"><button className="assessment-secondary" onClick={() => setDeleteGoalId(null)}>Cancel</button><button className="danger-button" onClick={() => deleteGoal(deleteGoalId)}>Delete goal</button></div></GoalModal>}</>;
}
