import React, { useState } from 'react';
import { ArrowRight, Check, Sparkles, X } from 'lucide-react';
import { calculateDimensionScore, microAssessmentQuestions, traitExplanation, traitScoreFromAnswers } from '../../data/swellTraitTaxonomy';

function TraitModal({ children, onClose }) { return <div className="trait-modal-backdrop"><section className="trait-modal"><button className="goal-modal-close" onClick={onClose} aria-label="Close"><X size={20} /></button>{children}</section></div>; }

export default function SwellTraits({ dashboardData, traitProfile, isOwnProfile, onTraitProfileChange, profile }) {
  const [dimensionId, setDimensionId] = useState(null); const [traitId, setTraitId] = useState(null); const [microAnswers, setMicroAnswers] = useState([]); const [microStarted, setMicroStarted] = useState(false); const [updateNote, setUpdateNote] = useState(null);
  const dimension = traitProfile?.find((item) => item.id === dimensionId); const trait = dimension?.traits.find((item) => item.id === traitId); const questions = trait ? microAssessmentQuestions(trait.name) : [];
  const openTrait = (item) => { setTraitId(item.id); setMicroAnswers([]); setMicroStarted(false); setUpdateNote(null); };
  const refine = () => { if (microAnswers.length !== questions.length || !trait) return; const evidence = traitScoreFromAnswers(microAnswers); const nextScore = Math.max(0, Math.min(100, Math.round((trait.score * 0.75) + (evidence * 0.25)))); const nextProfile = traitProfile.map((item) => item.id !== dimension.id ? item : { ...item, traits: item.traits.map((currentTrait) => currentTrait.id !== trait.id ? currentTrait : { ...currentTrait, score: nextScore, history: [...currentTrait.history, { score: nextScore, source: 'micro-assessment', date: new Date().toISOString() }] }) }); const recalculated = nextProfile.map((item) => ({ ...item, score: calculateDimensionScore(item.traits) })); onTraitProfileChange(recalculated); setUpdateNote({ from: trait.score, to: nextScore }); setMicroAnswers([]); };

  return <><div className="page-intro"><h2>Traits</h2><p>{isOwnProfile ? 'Your profile' : `${profile.name.split(' ')[0]}'s profile`} is built from 63 evolving traits across 9 workplace dimensions.</p></div><div className="traits-grid">{traitProfile.map((item) => <article className="card trait-card dimension-launch" key={item.id} onClick={() => setDimensionId(item.id)}><div className="trait-card-top"><h3>{item.name}</h3><strong>{item.score}%</strong></div><div className="bar large"><i className={dashboardData.workplaceDimensions.find((dimension) => dimension.id === item.id)?.color ?? 'violet'} style={{ width: `${item.score}%` }} /></div><p>{dashboardData.workplaceDimensions.find((dimension) => dimension.id === item.id)?.description}</p><span className="dimension-open">View 7 traits <ArrowRight size={14} /></span></article>)}</div>
  {dimension && !trait && <TraitModal onClose={() => setDimensionId(null)}><div className="trait-detail-header"><span>{dimension.name.toUpperCase()}</span><h2>{dimension.name} <b>{dimension.score}%</b></h2><p>{dashboardData.workplaceDimensions.find((item) => item.id === dimension.id)?.description}</p></div><div className="trait-list-heading">TRAITS</div><div className="trait-detail-list">{dimension.traits.map((item) => <button key={item.id} onClick={() => openTrait(item)}><span>{item.name}</span><b>{item.score}%</b><ArrowRight size={15} /></button>)}</div></TraitModal>}
  {dimension && trait && <TraitModal onClose={() => { setTraitId(null); setMicroAnswers([]); setMicroStarted(false); }}><div className="trait-detail-header"><span>{dimension.name.toUpperCase()}</span><h2>{trait.name} <b>{trait.score}%</b></h2></div>{updateNote ? <div className="trait-update-note"><Check size={16} /> {updateNote.from}% → {updateNote.to}% <span>Updated with new profile evidence.</span></div> : microStarted ? <div className="micro-assessment">{microAnswers.length < questions.length ? <><span>REFINE THIS TRAIT · {microAnswers.length + 1} / {questions.length}</span><h3>{questions[microAnswers.length].prompt}</h3>{questions[microAnswers.length].choices.map((choice, index) => <button key={choice} onClick={() => setMicroAnswers([...microAnswers, index])}>{choice}</button>)}</> : <><span>REFINE THIS TRAIT · COMPLETE</span><h3>Apply this new evidence to your trait profile?</h3><button className="assessment-primary" onClick={refine}>Apply refinement</button></>}</div> : <div className="trait-explanation"><section><span>WHAT THIS MEASURES</span><p>{traitExplanation(trait, dimension).measures}</p></section><section><span>AT WORK</span><p>{traitExplanation(trait, dimension).work}</p></section><section><span>YOUR CURRENT PATTERN</span><p>{traitExplanation(trait, dimension).interpretation}</p></section>{isOwnProfile && <><section className="trait-history"><span>PROFILE HISTORY</span>{trait.history.map((entry, index) => <p key={`${entry.date}-${index}`}>{entry.score}% <em>{entry.source.replace('-', ' ')}</em></p>)}</section><button className="assessment-primary" onClick={() => setMicroStarted(true)}><Sparkles size={16} /> Refine this trait</button></>}</div>}</TraitModal>}</>;
}
