import bcrypt from 'bcryptjs';
import { db } from './db.js';

const dimensionNames = ['Identity & Drive', 'Mind & Reasoning', 'Communication', 'Collaboration', 'Leadership & Influence', 'Adaptability', 'Conflict & Repair', 'Execution & Work Style', 'Social Presence'];
const colors = ['violet', 'blue', 'pink', 'indigo', 'teal', 'amber', 'violet', 'blue', 'teal'];
const details = ['What motivates you and how you orient around purpose, autonomy, and goals.', 'How you interpret information, solve problems, and form decisions.', 'How you share context, listen, and adapt messages for different audiences.', 'How you partner, build trust, and contribute within shared work.', 'How you create direction, build alignment, and help others succeed.', 'How you respond constructively to change, uncertainty, and shifting priorities.', 'How you navigate disagreement, feedback, and rebuilding alignment.', 'How you plan, prioritize, and turn commitments into progress.', 'How you show up in groups and make space for productive connection.'];

function swellData(user, config) {
  const profile = { name: user.displayName, initials: user.initials, title: user.jobTitle, department: user.department, archetype: config.archetype, personality: config.mbti, confidence: config.confidence, labels: config.labels, description: config.description, archetypeExplanation: 'Your archetype is an entry point into a broader workplace profile built from 63 evolving traits.' };
  const scores = config.dimensionScores;
  return { profile, traits: [
    { name: 'Analytical', score: config.work.analytical, detail: 'How you use evidence and patterns to make sense of work.', color: 'blue' },
    { name: 'Independence', score: config.work.independence, detail: 'How comfortably you own work and make progress autonomously.', color: 'violet' },
    { name: 'Goal Orientation', score: config.work.goalOrientation, detail: 'How strongly outcomes and purposeful progress focus your effort.', color: 'teal' },
    { name: 'Adaptability', score: config.work.adaptability, detail: 'How you adjust constructively when priorities change.', color: 'amber' },
    { name: 'Communication', score: config.work.communication, detail: 'How you share context and tailor messages to an audience.', color: 'pink' },
    { name: 'Collaboration', score: config.work.collaboration, detail: 'How you build alignment and contribute in shared work.', color: 'indigo' },
  ], workplaceDimensions: dimensionNames.map((name, index) => ({ id: name.toLowerCase().replaceAll(' & ', '-').replaceAll(' ', '-'), name, score: scores[index], color: colors[index], description: details[index], traits: [] })), strengths: config.strengths, growthAreas: config.growthAreas, collaborationSnapshot: config.collaboration, goals: config.goals, communicationTrend: [{ week: 'Week 1', value: Math.max(50, config.work.communication - 8) }, { week: 'Week 4', value: Math.max(54, config.work.communication - 4) }, { week: 'Week 8', value: config.work.communication }], communicationPreferences: config.communicationPreferences };
}

const users = [
  { key: 'EO', email: 'enoch@swollenteams.demo', firstName: 'Enoch', lastName: 'Olukolajo', displayName: 'Enoch Olukolajo', initials: 'EO', jobTitle: 'Product Team Member', department: 'PSC', current: 1, config: { archetype: 'Strategist', mbti: 'INTJ', confidence: 78, labels: ['Analytical', 'Independent', 'Goal-oriented'], description: 'You bring structured thinking to complex work, pairing a clear point of view with a focus on meaningful outcomes.', work: { analytical: 91, independence: 84, goalOrientation: 88, adaptability: 71, communication: 62, collaboration: 63 }, dimensionScores: [86, 91, 62, 63, 74, 71, 68, 88, 66], strengths: ['Strategic thinking', 'Problem solving', 'Planning'], growthAreas: ['Communication flexibility', 'Delegation', 'Adaptability'], collaboration: { bestWith: ['Clear objectives', 'Defined ownership', 'Time to analyze problems'], friction: ['Ambiguous responsibilities', 'Rapid decisions without context', 'Highly unstructured collaboration'], tip: 'Provide clear objectives and context, then allow room to determine the approach.' }, goals: [], communicationPreferences: ['Prefers context before decisions', 'Values concise, evidence-based communication', 'Responds well to clear ownership'] } },
  { key: 'PM', email: 'patrick@swollenteams.demo', firstName: 'Patrick', lastName: 'McDonald', displayName: 'Patrick McDonald', initials: 'PM', jobTitle: 'Air Compliance Supervisor', department: 'PSC', current: 0, config: { archetype: 'Strategist', mbti: 'INTJ', confidence: 78, labels: ['Analytical', 'Independent', 'Goal-oriented'], description: 'You bring structured thinking to complex work, pairing a clear point of view with a focus on meaningful outcomes.', work: { analytical: 91, independence: 84, goalOrientation: 88, adaptability: 71, communication: 62, collaboration: 63 }, dimensionScores: [86, 91, 62, 63, 74, 71, 68, 88, 66], strengths: ['Strategic thinking', 'Problem solving', 'Planning'], growthAreas: ['Communication flexibility', 'Delegation', 'Adaptability'], collaboration: { bestWith: ['Clear objectives', 'Defined ownership', 'Time to analyze problems'], friction: ['Ambiguous responsibilities', 'Rapid decisions without context', 'Highly unstructured collaboration'], tip: 'Provide clear objectives and context, then allow room to determine the approach.' }, goals: [], communicationPreferences: ['Prefers context before decisions', 'Values concise, evidence-based communication', 'Responds well to clear ownership'] } },
  { key: 'AC', email: 'alex@swollenteams.demo', firstName: 'Alex', lastName: 'Carter', displayName: 'Alex Carter', initials: 'AC', jobTitle: 'Operations Analyst', department: 'PSC', current: 0, config: { archetype: 'Connector', mbti: 'ENFJ', confidence: 76, labels: ['Communicative', 'Collaborative', 'Adaptable'], description: 'You build momentum by helping people share context, coordinate their efforts, and feel included in the work.', work: { analytical: 68, independence: 58, goalOrientation: 79, adaptability: 86, communication: 91, collaboration: 94 }, dimensionScores: [76, 68, 91, 94, 79, 86, 82, 72, 90], strengths: ['Team coordination', 'Communication', 'Relationship building'], growthAreas: ['Independent decision making', 'Analytical depth', 'Boundary setting'], collaboration: { bestWith: ['Shared problem solving', 'Frequent alignment', 'Open communication'], friction: ['Isolated decision making', 'Poor communication', 'Work that lacks collaboration'], tip: 'Use regular alignment points to connect perspectives and turn shared context into action.' }, goals: [], communicationPreferences: ['Shares context early', 'Invites perspectives', 'Builds alignment through conversation'] } },
  { key: 'JT', email: 'jordan@swollenteams.demo', firstName: 'Jordan', lastName: 'Taylor', displayName: 'Jordan Taylor', initials: 'JT', jobTitle: 'Project Coordinator', department: 'PSC', current: 0, config: { archetype: 'Catalyst', mbti: 'ENTP', confidence: 72, labels: ['Adaptable', 'Inventive', 'Independent'], description: 'You spot possibilities quickly, test ideas in motion, and help teams find practical paths through uncertainty.', work: { analytical: 81, independence: 82, goalOrientation: 73, adaptability: 92, communication: 78, collaboration: 75 }, dimensionScores: [82, 81, 78, 75, 72, 92, 70, 66, 80], strengths: ['Adaptability', 'Problem solving', 'Creative thinking'], growthAreas: ['Consistency', 'Follow-through', 'Structured planning'], collaboration: { bestWith: ['Flexible teams', 'Iterative work', 'Changing priorities'], friction: ['Overly rigid processes', 'Excessive approvals', 'Plans that cannot adapt'], tip: 'Share your evolving thinking early, then align the team on what is changing and why.' }, goals: [], communicationPreferences: ['Explores options openly', 'Adapts quickly to new context', 'Brings energy to working sessions'] } },
];

db.exec('DELETE FROM messages; DELETE FROM conversation_members; DELETE FROM conversations; DELETE FROM profiles; DELETE FROM users;');
const passwordHash = bcrypt.hashSync('demo123', 10);
const insertUser = db.prepare('INSERT INTO users (email,password_hash,first_name,last_name,display_name,initials,job_title,department,status,is_current_user) VALUES (?,?,?,?,?,?,?,?,?,?)');
const insertProfile = db.prepare(`INSERT INTO profiles (user_id,bio,organization,profile_complete,swell_archetype,mbti,swell_confidence,analytical,independence,goal_orientation,adaptability,communication,collaboration,identity_drive,mind_reasoning,leadership_influence,conflict_repair,execution_work_style,social_presence,strengths_json,growth_areas_json,collaboration_json,goals_json,growth_history_json,swell_data_json,assessment_responses_json,assessment_state_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);
const ids = {};
for (const entry of users) {
  const result = insertUser.run(entry.email, passwordHash, entry.firstName, entry.lastName, entry.displayName, entry.initials, entry.jobTitle, entry.department, 'Available', entry.current);
  ids[entry.key] = result.lastInsertRowid;
  const isInitialEO = entry.current === 1;
  const data = isInitialEO ? {} : swellData(entry, entry.config);
  const work = entry.config.work; const dimensions = entry.config.dimensionScores;
  const generated = isInitialEO
    ? [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
    : [entry.config.archetype, entry.config.mbti, entry.config.confidence, work.analytical, work.independence, work.goalOrientation, work.adaptability, work.communication, work.collaboration, dimensions[0], dimensions[1], dimensions[4], dimensions[6], dimensions[7], dimensions[8]];
  insertProfile.run(result.lastInsertRowid, `${entry.displayName} is a member of the PSC team.`, 'PSC', isInitialEO ? 0 : 1, ...generated, JSON.stringify(isInitialEO ? [] : entry.config.strengths), JSON.stringify(isInitialEO ? [] : entry.config.growthAreas), JSON.stringify(isInitialEO ? {} : entry.config.collaboration), JSON.stringify([]), JSON.stringify(isInitialEO ? [] : data.communicationTrend), JSON.stringify(data), JSON.stringify({}), JSON.stringify({ status: 'welcome', currentIndex: 0 }));
}
const insertConversation = db.prepare('INSERT INTO conversations (type,created_by,created_at,updated_at) VALUES (?,?,?,?)');
const insertMember = db.prepare('INSERT INTO conversation_members (conversation_id,user_id) VALUES (?,?)');
const insertMessage = db.prepare('INSERT INTO messages (conversation_id,sender_id,body,created_at,updated_at) VALUES (?,?,?,?,?)');
const createConversation = (type, members, messages) => { const start = new Date(Date.now() - 60 * 60 * 1000); const result = insertConversation.run(type, ids.EO, start.toISOString(), start.toISOString()); const id = result.lastInsertRowid; members.forEach((member) => insertMember.run(id, ids[member])); messages.forEach(([sender, body, minutes]) => { const time = new Date(Date.now() - minutes * 60000).toISOString(); insertMessage.run(id, ids[sender], body, time, time); }); const latest = messages.at(-1); if (latest) db.prepare('UPDATE conversations SET updated_at=? WHERE id=?').run(new Date(Date.now() - latest[2] * 60000).toISOString(), id); };
createConversation('self', ['EO'], []);
createConversation('dm', ['EO', 'PM'], [['PM', "Here's the latest project update.", 42], ['PM', 'Let me know what you think.', 38], ['EO', "Thanks, I'll review it.", 35]]);
createConversation('dm', ['EO', 'AC'], [['AC', 'I added the notes to the board.', 95], ['EO', 'Great, thank you.', 91]]);
createConversation('dm', ['EO', 'JT'], [['JT', 'Sounds good to me.', 1440]]);
console.log('Seeded Swollen Teams demo database.');
