import React, { useEffect, useRef, useState } from 'react';
import './shell.css';
import './layout.css';
import './self-chat.css';
import './navigation.css';
import { Activity, AtSign, Bell, CalendarDays, ChevronDown, ChevronRight, Ellipsis, FileText, Grid2X2, MessageSquare, MoreHorizontal, Paperclip, Phone, Plus, Search, Send, Smile, Sparkles, Trash2, Users, Video } from 'lucide-react';
import SwellProfile from './components/swell/SwellProfile';
import { contacts as fallbackContacts, initialConversations, selfConversation as fallbackSelfConversation } from './data/chatMockData';
import { createInitialProfileStates, currentUserId, generateInitialSwellProfile, recalculateSwellProfileFromTraits, swellProfiles } from './data/swellMockData';
import { loadSwellGoals, saveSwellGoals } from './data/swellGoals';
import { getConversations, getCurrentUser, getMessages, getUserProfile, getUsers, saveMyAssessment, sendMessage as sendMessageRequest } from './services/api';

const loadProfileStates = () => { const initialStates = createInitialProfileStates(); try { const storedEO = window.localStorage.getItem('swellProfileState:eo'); const storedTraits = window.localStorage.getItem('swellTraitProfile:eo'); const parsedEO = storedEO ? JSON.parse(storedEO) : null; return parsedEO ? { ...initialStates, EO: { ...initialStates.EO, ...parsedEO, swellProfile: parsedEO.swellProfile && storedTraits ? { ...parsedEO.swellProfile, traitProfile: JSON.parse(storedTraits) } : parsedEO.swellProfile } } : initialStates; } catch { return initialStates; } };
const now = () => new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date());

function SimpleProfile({ contact, onClose }) { return <div className="modal-backdrop"><section className="profile-modal simple-contact-modal"><button className="modal-close" onClick={onClose}>×</button><div className="simple-contact-avatar">{contact.initials}</div><h1>{contact.name}</h1><p>{contact.role}</p><div className="placeholder-panel"><p>Swell profile not available</p><span>This contact’s full Swell profile has not been created yet.</span></div></section></div>; }

function SelfNotes({ notes, activeNoteId, onCreate, onSelect, onUpdate, onDelete }) { const activeNote = notes.find((note) => note.id === activeNoteId); if (!activeNote) return <section className="self-notes"><div className="self-notes-heading"><div><h2>Notes</h2><p>Keep private drafts, reminders, and working thoughts together.</p></div><button className="new-note" onClick={onCreate}><Plus size={16} /> New note</button></div>{notes.length ? <div className="note-list">{notes.map((note) => <button key={note.id} className="note-card" onClick={() => onSelect(note.id)}><b>{note.title || 'Untitled note'}</b><span>{note.body || 'No content yet'}</span><small>Edited {note.updatedAt}</small></button>)}</div> : <div className="self-empty-state"><FileText size={25} /><h2>No notes yet</h2><p>Create a note to keep your ideas close at hand.</p></div>}</section>; return <section className="self-notes"><div className="self-notes-heading"><button className="notes-back" onClick={() => onSelect(null)}>‹ Notes</button><button className="new-note" onClick={onCreate}><Plus size={16} /> New note</button></div><div className="note-editor"><input aria-label="Note title" value={activeNote.title} placeholder="Note title" onChange={(event) => onUpdate(activeNote.id, { title: event.target.value })} /><textarea aria-label="Note body" value={activeNote.body} placeholder="Start writing..." onChange={(event) => onUpdate(activeNote.id, { body: event.target.value })} /><div><small>Last edited {activeNote.updatedAt}</small><button className="delete-note" onClick={() => onDelete(activeNote.id)}><Trash2 size={15} /> Delete</button></div></div></section>; }

export default function App() {
  const [selectedProfile, setSelectedProfile] = useState(null); const [simpleProfile, setSimpleProfile] = useState(null); const [profileStates, setProfileStates] = useState(loadProfileStates); const [goalsByUser, setGoalsByUser] = useState(() => ({ [currentUserId]: loadSwellGoals(currentUserId) }));
  const [activeAppSection, setActiveAppSection] = useState('chat'); const [selectedConversationId, setSelectedConversationId] = useState('PM'); const [conversations, setConversations] = useState(initialConversations); const [composer, setComposer] = useState(''); const [chatTab, setChatTab] = useState('Chat'); const [toast, setToast] = useState(''); const [searchQuery, setSearchQuery] = useState(''); const [notes, setNotes] = useState([]); const [activeNoteId, setActiveNoteId] = useState(null); const [favoritesExpanded, setFavoritesExpanded] = useState(true); const [chatsExpanded, setChatsExpanded] = useState(true); const [apiCurrentUser, setApiCurrentUser] = useState(null); const [apiConversations, setApiConversations] = useState([]); const [apiProfiles, setApiProfiles] = useState({}); const [apiError, setApiError] = useState(''); const messagesEndRef = useRef(null);
  const usingApi = apiConversations.length > 0;
  const selfConversation = usingApi ? apiConversations.find((conversation) => conversation.type === 'self') : fallbackSelfConversation;
  const contacts = usingApi ? apiConversations.filter((conversation) => conversation.type !== 'self').map((conversation) => ({ id: conversation.id, userId: conversation.otherUser?.id, name: conversation.name, initials: conversation.otherUser?.initials, status: conversation.otherUser?.status || 'Available', role: conversation.otherUser?.jobTitle && conversation.otherUser?.department ? `${conversation.otherUser.jobTitle} · ${conversation.otherUser.department}` : '', preview: conversation.lastMessage?.body || 'No messages yet', time: conversation.lastMessage ? new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date(conversation.lastMessage.createdAt)) : '' })) : fallbackContacts;
  const isSelfChat = selectedConversationId === selfConversation?.id;
  const selectedContact = isSelfChat ? { ...selfConversation, status: 'You', name: apiCurrentUser?.displayName || fallbackSelfConversation.name, initials: apiCurrentUser?.initials || 'EO' } : (contacts.find((contact) => contact.id === selectedConversationId) ?? contacts[0]);
  const closeProfile = () => { setSelectedProfile(null); setSimpleProfile(null); };
  const loadApiProfile = async (userId) => { try { const profile = await getUserProfile(userId); setApiProfiles((current) => ({ ...current, [userId]: profile })); return profile; } catch (error) { console.error('Unable to load profile', error); setApiError('Unable to load profile data.'); return null; } };
  const openOwnProfile = async () => { if (usingApi && apiCurrentUser) { setSelectedProfile(apiCurrentUser.id); await loadApiProfile(apiCurrentUser.id); } else setSelectedProfile('EO'); };
  const openContactProfile = async (contact) => { if (usingApi && contact?.userId) { setSelectedProfile(contact.userId); await loadApiProfile(contact.userId); } else if (contact?.id === 'PM') setSelectedProfile('PM'); else setSimpleProfile(contact); };
  const updateApiProfile = (profile) => setApiProfiles((current) => ({ ...current, [profile.user.id]: profile }));
  const updateAssessment = (assessment) => {
    setProfileStates((states) => ({ ...states, EO: { ...states.EO, assessment } }));
    if (usingApi && apiCurrentUser) saveMyAssessment({ responses: assessment.responses, status: assessment.status, currentIndex: assessment.currentIndex, complete: false }).then(updateApiProfile).catch((error) => { console.error('Unable to save assessment progress', error); setApiError('Assessment progress could not be saved.'); });
  };
  const completeAssessment = async (responses) => {
    const generatedProfile = generateInitialSwellProfile(swellProfiles.EO.profile, responses);
    setProfileStates((states) => ({ ...states, EO: { ...states.EO, profileCompleted: true, assessment: { ...states.EO.assessment, status: 'dashboard', responses, completed: true, currentIndex: 8 }, swellProfile: generatedProfile } }));
    if (usingApi && apiCurrentUser) {
      try { updateApiProfile(await saveMyAssessment({ responses, status: 'dashboard', currentIndex: 8, complete: true, swellProfile: generatedProfile })); }
      catch (error) { console.error('Unable to complete assessment', error); setApiError('Your Swell profile could not be saved.'); }
    }
  };
  const updateGoals = (userId, goals) => setGoalsByUser((existing) => ({ ...existing, [userId]: goals }));
  const updateTraitProfile = (traitProfile) => setProfileStates((states) => ({ ...states, EO: { ...states.EO, swellProfile: recalculateSwellProfileFromTraits(states.EO.swellProfile, traitProfile) } }));
  const selectConversation = (id) => { setSelectedConversationId(id); setActiveAppSection('chat'); setChatTab('Chat'); setSearchQuery(''); };
  const showToast = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2200); };
  const sendMessage = async (text = composer) => { const clean = text.trim(); if (!clean || !selectedConversationId) return; if (usingApi) { try { const { message } = await sendMessageRequest(selectedConversationId, clean); setConversations((current) => ({ ...current, [selectedConversationId]: [...(current[selectedConversationId] || []), { id: message.id, senderId: message.sender.id, text: message.body, timestamp: new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date(message.createdAt)) }] })); setComposer(''); const { conversations: refreshed } = await getConversations(); setApiConversations(refreshed); } catch (error) { console.error('Unable to send message', error); setApiError('Message could not be sent.'); } return; } setConversations((current) => ({ ...current, [selectedConversationId]: [...current[selectedConversationId], { id: `eo-${Date.now()}`, senderId: 'EO', text: clean, timestamp: now() }] })); setComposer(''); };
  const createNote = () => { const note = { id: `note-${Date.now()}`, title: '', body: '', updatedAt: now() }; setNotes((current) => [...current, note]); setActiveNoteId(note.id); };
  const updateNote = (id, changes) => setNotes((current) => current.map((note) => note.id === id ? { ...note, ...changes, updatedAt: now() } : note));
  const deleteNote = (id) => { setNotes((current) => current.filter((note) => note.id !== id)); setActiveNoteId(null); };
  useEffect(() => { saveSwellGoals(currentUserId, goalsByUser[currentUserId] ?? []); }, [goalsByUser]);
  useEffect(() => { window.localStorage.setItem('swellProfileState:eo', JSON.stringify(profileStates.EO)); }, [profileStates.EO]);
  useEffect(() => { if (profileStates.EO.swellProfile?.traitProfile) window.localStorage.setItem('swellTraitProfile:eo', JSON.stringify(profileStates.EO.swellProfile.traitProfile)); }, [profileStates.EO.swellProfile]);
  useEffect(() => { let active = true; (async () => { try { const { user } = await getCurrentUser(); const [{ conversations: loadedConversations }, { users }] = await Promise.all([getConversations(), getUsers()]); if (!active) return; setApiCurrentUser(user); setApiConversations(loadedConversations); const profiles = await Promise.all(users.map(async (entry) => [entry.id, await getUserProfile(entry.id)])); if (!active) return; const profileMap = Object.fromEntries(profiles); setApiProfiles(profileMap); const eoProfile = profileMap[user.id]; if (eoProfile && !eoProfile.profile.profileComplete) { window.localStorage.removeItem('swellProfileState:eo'); window.localStorage.removeItem('swellTraitProfile:eo'); window.localStorage.removeItem('swellGoals:eo'); setProfileStates((states) => ({ ...states, EO: { ...createInitialProfileStates().EO, assessment: eoProfile.assessment } })); setGoalsByUser((goals) => ({ ...goals, [currentUserId]: [] })); } const patrick = loadedConversations.find((conversation) => conversation.type === 'dm' && conversation.otherUser?.initials === 'PM'); setSelectedConversationId(patrick?.id ?? loadedConversations[0]?.id ?? 'PM'); } catch (error) { console.error('API initialization failed; using local demo fallback.', error); if (active) setApiError('Backend unavailable — showing local demo data.'); } })(); return () => { active = false; }; }, []);
  useEffect(() => { if (!usingApi || !selectedConversationId || !apiConversations.some((conversation) => conversation.id === selectedConversationId)) return; let active = true; getMessages(selectedConversationId).then(({ messages }) => { if (active) setConversations((current) => ({ ...current, [selectedConversationId]: messages.map((message) => ({ id: message.id, senderId: message.sender.id, text: message.body, timestamp: new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date(message.createdAt)) })) })); }).catch((error) => { console.error('Unable to load messages', error); setApiError('Unable to load conversation messages.'); }); return () => { active = false; }; }, [usingApi, apiConversations, selectedConversationId]);
  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [conversations, selectedConversationId]);
  useEffect(() => { const onKey = (event) => { if (event.key === 'Escape') closeProfile(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  useEffect(() => { const previousOverflow = document.body.style.overflow; if (selectedProfile || simpleProfile) document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = previousOverflow; }; }, [selectedProfile, simpleProfile]);
  const searchResults = [...contacts, { id: 'EO', name: 'Enoch Olukolajo', initials: 'EO', role: 'Product Team Member · PSC' }].filter((person) => person.name.toLowerCase().includes(searchQuery.toLowerCase()));
  const railItems = [{ id: 'activity', label: 'Activity', icon: Activity }, { id: 'chat', label: 'Chat', icon: MessageSquare }, { id: 'calendar', label: 'Calendar', icon: CalendarDays }, { id: 'people', label: 'People', icon: Users }, { id: 'calls', label: 'Calls', icon: Phone }, { id: 'swell-agent', label: 'Swell Agent', icon: Sparkles }];

  const renderComposer = () => <><div className="quick-replies">{['Thanks', 'Let me check', 'Got it, thanks'].map((reply) => <button key={reply} onClick={() => sendMessage(reply)}>{reply}</button>)}</div><div className="composer"><div className="composer-tools"><button onClick={() => showToast('Formatting options coming soon')}><AtSign size={18} /></button><button onClick={() => showToast('Attachments coming soon')}><Paperclip size={18} /></button><button onClick={() => showToast('Emoji picker coming soon')}><Smile size={18} /></button><button onClick={() => showToast('More composer options coming soon')}><Plus size={18} /></button></div><textarea aria-label="Message composer" value={composer} onChange={(event) => setComposer(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); sendMessage(); } }} placeholder={isSelfChat ? 'Message yourself' : `Message ${selectedContact.name}`} /><button className="send-message" disabled={!composer.trim()} onClick={() => sendMessage()}><Send size={18} /></button></div></>;
  const renderChatBody = () => {
    if (isSelfChat && chatTab === 'Notes') return <SelfNotes notes={notes} activeNoteId={activeNoteId} onCreate={createNote} onSelect={setActiveNoteId} onUpdate={updateNote} onDelete={deleteNote} />;
    if (chatTab !== 'Chat') return <div className="chat-placeholder"><FileText size={28} /><h2>{chatTab}</h2><p>{chatTab === 'Shared' ? 'No shared files yet.' : chatTab === 'Notes' ? 'No notes yet.' : 'Recap is coming soon.'}</p></div>;
    const messages = conversations[selectedConversationId] ?? [];
    return <>{messages.length ? <div className="message-scroll">{messages.map((message, index) => { const outgoing = usingApi ? message.senderId === apiCurrentUser?.id : message.senderId === 'EO'; const previous = messages[index - 1]; const showName = !isSelfChat && !outgoing && (!previous || previous.senderId !== message.senderId); return <div className={`message-row ${outgoing ? 'outgoing' : 'incoming'}`} key={message.id}><div className="message-bubble">{showName && <b>{selectedContact.name}</b>}<span>{message.text}</span><time>{message.timestamp}</time></div></div>; })}<div ref={messagesEndRef} /></div> : isSelfChat ? <div className="self-chat-empty"><MessageSquare size={30} /><h2>This is your space</h2><p>This chat is just for you. Use it for drafts, reminders, notes, or anything you want to keep handy.</p></div> : <div className="message-scroll" ref={messagesEndRef} />} {renderComposer()}</>;
  };
  const renderSection = () => {
    if (activeAppSection === 'chat') {
      const tabs = isSelfChat ? ['Chat', 'Notes'] : ['Chat', 'Shared', 'Notes', 'Recap'];
      const SectionToggle = ({ label, expanded, onToggle }) => <button className="chat-section-toggle" onClick={onToggle}>{expanded ? <ChevronDown size={15} /> : <ChevronRight size={15} />}<span>{label}</span></button>;
      return <><aside className="chat-list"><div className="chat-list-heading"><h1>Chat</h1><button onClick={() => showToast('New chat coming soon')}><Plus size={18} /></button></div><section className="chat-section"><SectionToggle label="Favorites" expanded={favoritesExpanded} onToggle={() => setFavoritesExpanded((value) => !value)} />{favoritesExpanded && <div className="favorite-user"><button className={isSelfChat ? 'selected' : ''} onClick={() => selectConversation(selfConversation?.id || 'self')}><i>EO</i><strong>{apiCurrentUser?.displayName || 'Enoch Olukolajo'}</strong><em>You</em></button></div>}</section><section className="chat-section"><SectionToggle label="Chats" expanded={chatsExpanded} onToggle={() => setChatsExpanded((value) => !value)} />{chatsExpanded && contacts.map((contact) => <button className={`conversation-row ${selectedConversationId === contact.id ? 'selected' : ''}`} key={contact.id} onClick={() => selectConversation(contact.id)}><i className={`person-dot ${contact.initials === 'AC' ? 'green' : contact.initials === 'JT' ? 'purple' : ''}`}>{contact.initials}</i><span><b>{contact.name}</b><small>{contact.preview}</small></span><time>{contact.time}</time></button>)}</section></aside><section className="chat-pane"><header className="conversation-header"><button className="contact-heading" onClick={() => isSelfChat ? openOwnProfile() : openContactProfile(selectedContact)}><i className={`person-dot ${selectedContact.initials === 'AC' ? 'green' : selectedContact.initials === 'JT' ? 'purple' : ''}`}>{selectedContact.initials}</i><span><b>{selectedContact.name}{isSelfChat && ' (You)'}</b><small>{selectedContact.status}</small></span></button><nav>{tabs.map((tab) => <button key={tab} className={chatTab === tab ? 'active' : ''} onClick={() => setChatTab(tab)}>{tab}</button>)}</nav>{!isSelfChat && <div className="header-actions"><button onClick={() => showToast('Calling feature coming soon')}><Phone size={18} /></button><button onClick={() => showToast('Calling feature coming soon')}><Video size={18} /></button><button onClick={() => openContactProfile(selectedContact)}><Users size={18} /></button><button onClick={() => showToast('Conversation search coming soon')}><Search size={18} /></button><button onClick={() => showToast('More actions coming soon')}><MoreHorizontal size={18} /></button></div>}</header>{renderChatBody()}</section></>;
    }
    if (activeAppSection === 'activity') return <><aside className="activity-panel"><div className="activity-panel-header"><h1>Activity</h1><div><button onClick={() => showToast('Activity options coming soon')}><MoreHorizontal size={17} /></button><button onClick={() => showToast('Activity search coming soon')}><Search size={17} /></button></div></div><div className="activity-filters"><button className="active">Unread</button><button>@Mentions</button><button>Tag mentions</button></div><p>You'll see @mentions, reactions, Swell insights, and other notifications here.</p></aside><section className="activity-workspace"><Activity size={30} /><p>Select an activity to view more details.</p></section></>;
    if (activeAppSection === 'swell-agent') return <section className="swell-agent-page"><div><span className="agent-kicker"><Sparkles size={15} /> Swell Agent</span><h1>Swell Agent</h1><p>Workplace intelligence powered by your evolving Swell profile.</p></div><div className="agent-actions">{['Prepare for a conversation', 'Understand a teammate', 'Improve team collaboration', 'Review my growth'].map((action) => <button key={action}><Sparkles size={17} /><span>{action}</span><small>Coming soon</small></button>)}</div></section>;
    const title = activeAppSection === 'calendar' ? 'Calendar prototype' : activeAppSection === 'people' ? 'People & teams' : 'Calls'; return <section className="app-placeholder"><div><Activity size={28} /><h1>{title}</h1><p>{activeAppSection === 'calendar' ? 'Calendar prototype — schedule management is coming soon.' : activeAppSection === 'people' ? 'Find the people you work with.' : 'Calls coming soon. Your recent calls will appear here.'}</p>{activeAppSection === 'people' && <div className="directory">{[{ id: 'EO', name: 'Enoch Olukolajo', initials: 'EO', role: 'Product Team Member · PSC' }, ...contacts].map((person) => <button key={person.id} onClick={() => person.id === 'EO' ? openOwnProfile() : person.userId ? openContactProfile(person) : person.id === 'PM' ? setSelectedProfile('PM') : setSimpleProfile(person)}><i>{person.initials}</i><span><b>{person.name}</b><small>{person.role}</small></span></button>)}</div>}</div></section>;
  };

  const selectedApiProfile = usingApi && selectedProfile ? apiProfiles[selectedProfile] : null;
  const apiModalProfile = selectedApiProfile ? (() => { const data = selectedApiProfile.swell?.data || {}; const profile = data.profile || { name: selectedApiProfile.user.displayName, initials: selectedApiProfile.user.initials, title: selectedApiProfile.user.jobTitle, department: selectedApiProfile.user.department, archetype: selectedApiProfile.swell.archetype, personality: selectedApiProfile.swell.mbti, confidence: selectedApiProfile.swell.confidence, labels: [], description: '', archetypeExplanation: '' }; return { profileData: { id: String(selectedApiProfile.user.id), viewer: selectedApiProfile.user.isCurrentUser ? 'currentUser' : 'teammate', profile }, profileState: { userId: String(selectedApiProfile.user.id), profileCompleted: selectedApiProfile.profile.profileComplete, assessment: selectedApiProfile.assessment ?? { status: 'welcome', currentIndex: 0, responses: {}, completed: false }, swellProfile: selectedApiProfile.profile.profileComplete ? { ...data, profile } : null } }; })() : null;

  return <main className="teams-shell"><aside className="rail" aria-label="Teams navigation"><span className="rail-mark" title="App launcher"><Grid2X2 size={20} /></span>{railItems.map(({ id, label, icon: Icon }) => <button key={id} title={label} aria-label={label} className={activeAppSection === id ? 'rail-active' : ''} onClick={() => setActiveAppSection(id)}><Icon size={21} /><small>{label}</small></button>)}<button title="More" aria-label="More" onClick={() => showToast('More apps coming soon')}><Ellipsis size={21} /><small>More</small></button></aside><section className="teams-workspace"><header className="teams-topbar"><span className="teams-mark">T</span><div className="global-search"><Search size={19} /><input value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} placeholder="Search (Ctrl+Alt+E)" />{searchQuery && <div className="search-results">{searchResults.length ? searchResults.map((person) => <button key={person.id} onClick={() => person.id === 'EO' ? (openOwnProfile(), setSearchQuery('')) : selectConversation(person.id)}><i>{person.initials}</i><span>{person.name}<small>{person.role}</small></span></button>) : <span>No people found</span>}</div>}</div><button className="topbar-icon" onClick={() => showToast('Activity coming soon')}><Bell size={19} /></button><button className="mini-avatar profile-trigger" onClick={openOwnProfile} aria-label="Open My Swell profile">EO</button></header><div className="workspace-body">{apiError && <div className="app-toast">{apiError}</div>}{renderSection()}</div></section>{toast && <div className="app-toast">{toast}</div>}{selectedProfile && <SwellProfile profileData={apiModalProfile?.profileData ?? swellProfiles[selectedProfile]} profileState={apiModalProfile?.profileState ?? profileStates[selectedProfile]} currentUserProfileState={apiCurrentUser && apiProfiles[apiCurrentUser.id] ? { swellProfile: { ...(apiProfiles[apiCurrentUser.id].swell.data || {}), profile: apiProfiles[apiCurrentUser.id].swell.data?.profile } } : profileStates[currentUserId]} goals={goalsByUser[currentUserId] ?? []} onGoalsChange={(goals) => updateGoals(currentUserId, goals)} onTraitProfileChange={updateTraitProfile} onAssessmentChange={updateAssessment} onAssessmentComplete={completeAssessment} onClose={closeProfile} />}{simpleProfile && <SimpleProfile contact={simpleProfile} onClose={closeProfile} />}</main>;
}
